version: v1.0.0.{build}
os: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'

before_build:
- cmd: >-
    dotnet restore src\Emitter.Server && dotnet restore src\Emitter.Runtime && dotnet restore src\Emitter.Storage.S3

build_script:
- cmd: >-
    dotnet pack src\Emitter.Runtime --configuration Release --version-suffix dev%APPVEYOR_BUILD_NUMBER% && dotnet pack src\Emitter.Storage.S3 --configuration Release --version-suffix dev%APPVEYOR_BUILD_NUMBER% && dotnet pack src\Emitter.Server --configuration Release  --version-suffix dev%APPVEYOR_BUILD_NUMBER%

test: off

artifacts:
- path: '**\*.nupkg'

deploy:
  - provider: Environment
    name: Public S3
    artifact: /.*\.nupkg/
    on:                 
      branch: master

  - provider: NuGet
    api_key:
      secure: rU+w5deWOMiUmQES2u4bz1o0ElWYIfjxKVokp+QUjjidbGiRJwK6s1LcTNRrAde3
    artifact: /.*\.nupkg/   
    on:
      branch: master